### ISSUE TITLE
License queries

### ISSUE THREAD

**Issue by tomalrussell** [souzamonteiro/cnatool#1]
Hi @souzamonteiro, I'm just getting going with the JOSS review and had a couple of queries around licensing:

- [x] The `LICENSE` file holds the boilerplate text of the Apache 2.0 license - at the bottom this needs the authorship details "Copyright [yyyy] [name of copyright owner]" - can you fill those out?
- [x] The short version of the license statement (see https://opensource.org/license/apache-2-0/ "Appendix" section) could be included as a section in the README - this is optional, but it's often the first place I'd look.
- [x] The README mentions multiple licenses, `COPYING` and `COPYING.LIB`, but I can't find those in the repository and I can't see any other reference to specific licenses. Can you clarify or remove those references?

**Comment by souzamonteiro** [comment]
Thanks for the suggestions. I implemented them all.
