### ISSUE TITLE
cnatool command-line import errors

### ISSUE THREAD

**Issue by tomalrussell** [souzamonteiro/cnatool#2]
Hi @souzamonteiro 

I've successfully installed `cnatool` as a command-line tool. This works both from a local checkout of the git repository, and from `npm`.

When running `cnatool`, I see several `require` errors:

```
$ cnatool
Cannot find module 'algebrite'
Require stack:
- /usr/lib/node_modules/cnatool/bin/cnatool.js
Cannot find module 'gpu.js'
Require stack:
- /usr/lib/node_modules/cnatool/bin/cnatool.js
Cannot find module 'web-worker'
Require stack:
- /usr/lib/node_modules/cnatool/bin/cnatool.js
Cannot find module 'cross-blob'
Require stack:
- /usr/lib/node_modules/cnatool/bin/cnatool.js
CNATool Command Line Interface (CLI)
Usage: cnatool [options] [network.net] [--] [arguments]
```

Should these packages somehow be specified as requirements?

Are there example commands that would fail without these modules?

**Comment by ati-ozgur** [comment]
I am also having the same errors. 
Please fix the package.json (https://github.com/souzamonteiro/cnatool/blob/main/package.json) so that dependencies will be automatically installed with "npm install -g cnatool" command

**Comment by tomalrussell** [comment]
`npm i -g cnatool` gives the same errors as before - an updated version should be pushed to npmjs.com/package/cnatool

`npm i` from a checkout of this repository at 8e6df7bf00acda3ab258f9cd8041cf4240ec7467 required several C/C++ libraries installing, all of which should be documented (and more, if I overlooked any that I happened to have already on this machine) - for me, on Ubuntu with a bit of guesswork from `pkg-config` error messages:
```
sudo apt install libx11-dev libxi-dev libgl1mesa-dev
```
Presumably these are required by a particular npm package - is it that `gpu.js` depends on `gl` depends on these libraries? ([gpu.js docs](https://www.npmjs.com/package/gpu.js/v/2.4.0#installation))

**Comment by souzamonteiro** [comment]
> `npm i -g cnatool` gives the same errors as before - an updated version should be pushed to npmjs.com/package/cnatool
> 
> `npm i` from a checkout of this repository at [8e6df7b](https://github.com/souzamonteiro/cnatool/commit/8e6df7bf00acda3ab258f9cd8041cf4240ec7467) required several C/C++ libraries installing, all of which should be documented (and more, if I overlooked any that I happened to have already on this machine) - for me, on Ubuntu with a bit of guesswork from `pkg-config` error messages:
> 
> ```
> sudo apt install libx11-dev libxi-dev libgl1mesa-dev
> ```
> 
> Presumably these are required by a particular npm package - is it that `gpu.js` depends on `gl` depends on these libraries? ([gpu.js docs](https://www.npmjs.com/package/gpu.js/v/2.4.0#installation))

I updated the package on NPM with the fixes. There are actually no C/C++ library dependencies that need to be installed manually.  Some Linux distributions do not include some libraries that are dependencies on Node.js packages and not on CNATOOL itself. I have tested the installation without any issues on Ubuntu 20.04 and Ubuntu 22.04. Either using "npm install cnatool", or entering the directory downloaded from github and typing "npm install .". Libraries that are missing from your system are used by OpenGL Dev System. The Mesa3D dev packages are currently only installed on some distributions if you install video card specific drivers. Can be it...

**Comment by tomalrussell** [comment]
Can confirm that the install from npmjs.com works for me with v2.0.6 :+1:

I would recommend linking through to those `gpu.js` installation instructions, `npm i` was failing for me without those header libraries (suggested as `mesa-common-dev libxi-dev`) available.. in case anyone else has the same setup issue.

(Out of the original scope of this issue, but worth mentioning: ideally, the basic software setup could be verified in a CI action - have you considered running the build script and test suite in a GitHub action or similar automated system?)

**Comment by tomalrussell** [comment]
Just running `build.sh` and `test.sh` - all seem to build and pass, but `maiascript` now requires `websql`: 

    Cannot find module 'websql'

I ran `npm i --save websql` to add the package, which fixes the warning. I'd recommend updating `package.json` in the repository.

**Comment by souzamonteiro** [comment]
> Just running `build.sh` and `test.sh` - all seem to build and pass, but `maiascript` now requires `websql`:
> 
> ```
> Cannot find module 'websql'
> ```
> 
> I ran `npm i --save websql` to add the package, which fixes the warning. I'd recommend updating `package.json` in the repository.

Hi:
I added the dependency in package.json. But none of the dependencies that were previously pointed out, in addition to this one, prevent the program from working. All are optional and were not placed in package.json to prevent installation on systems where they are not supported. For example, websql and gpu.js will not install on some Linux distributions and some versions of node.js. I can't maintain support for all Linux distributions and versions of node.js. Nor is it the scope of this project. The program is only tested on Ubuntu 20.04 and 22.04 and just download from github in zip format for Windows. I don't recommend installing via npm on Windows because the dependencies that were included may not be supported. However, the HTML GUI will work on all platforms, including Android and iOS. But the program must be downloaded directly from github.
