### ISSUE TITLE
How to use examples

### ISSUE THREAD

**Issue by tomalrussell** [souzamonteiro/cnatool#4]
How should a new user find or make use of the [example files](https://github.com/souzamonteiro/cnatool/tree/main/examples)? 

I'd suggest adding a section to the documentation - how to load examples into the web tool, or how to run them through the command-line tool, and then what to expect or look for in the tool/output. What are the examples meant to illustrate?

What are the sources of these datasets? Are any of them synthetic or created just for this project? I'd suggest adding citations and references as appropriate.

**Comment by ati-ozgur** [comment]
I would like this also either in readme or in documentation. This usage should be linked to if it is not in the readme.

**Comment by souzamonteiro** [comment]
> How should a new user find or make use of the [example files](https://github.com/souzamonteiro/cnatool/tree/main/examples)?
> 
> I'd suggest adding a section to the documentation - how to load examples into the web tool, or how to run them through the command-line tool, and then what to expect or look for in the tool/output. What are the examples meant to illustrate?
> 
> What are the sources of these datasets? Are any of them synthetic or created just for this project? I'd suggest adding citations and references as appropriate.

The article originally had 3000 words, where all the information that has been requested was duly cited, but it was requested that the article be reduced to 100 words, which greatly impaired the quality of the work.

**Comment by tomalrussell** [comment]
Could some of those 3000 words be added to the README or documentation? That would still be useful for users of the tool, even if it's not in scope for the paper.

**Comment by souzamonteiro** [comment]
> How should a new user find or make use of the [example files](https://github.com/souzamonteiro/cnatool/tree/main/examples)?
> 
> I'd suggest adding a section to the documentation - how to load examples into the web tool, or how to run them through the command-line tool, and then what to expect or look for in the tool/output. What are the examples meant to illustrate?
> 
> What are the sources of these datasets? Are any of them synthetic or created just for this project? I'd suggest adding citations and references as appropriate.

USING THE SAMPLE FILES

They were created by the author and are available under the same license as the program. I noticed that there were some files created by students that were exclusive to their master's projects. I removed them and put a pointer about the example files in README.md.
