### ISSUE TITLE
please divide introduction paragraph

### ISSUE THREAD

**Issue by ati-ozgur** [souzamonteiro/cnatool#6]
As it is introduction first paragraph is too long with again long sentences, making it very hard to read. Please divide it to several paragraphs and change very long sentences with proper connection verbs to make it easier to understand.

**Comment by souzamonteiro** [comment]
> As it is introduction first paragraph is too long with again long sentences, making it very hard to read. Please divide it to several paragraphs and change very long sentences with proper connection verbs to make it easier to understand.

Done.
